# .github/workflows/translate.yml
name: Translate Readme

on:
    push:
        branches: ['**']

jobs:
    translate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 3

            - name: Auto Translate
              uses: Lin-jun-xiang/action-translate-readme@v2 # Based on the tag
              with:
                token: ${{ secrets.ACTION }} # Based on step2 name
                zhipuai: ${{ secrets.ZHIPU }} # Optional: Based on step3
                openai: ${{ secrets.openai_api_key }}  # Optional: Based on step3
                langs: "en" # You can define any langs
