# .github/workflows/translate.yml
name: Translate Readme

on:
    push:
        branches: ['**']

jobs:
    translate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 3

            - name: Auto Translate
              uses: Lin-jun-xiang/action-translate-readme@v2 
              with:
                token: ${{ secrets.action }} 
                zhipuai: ${{ secrets.zhipu }} 
                # openai: ${{ secrets.openai_api_key }}  
                langs: "en,zh-TW,zh-CN,French,Arabic" 
